Update deployment workflow to use GitHub secrets for PostgreSQL credentials and configure Nginx for SSL

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -43,15 +43,56 @@ jobs:
 
           cd /home/AttackVisualizer
 
-          export POSTGRES_USER=${POSTGRES_USER}
-          export POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
-          export POSTGRES_DB=${POSTGRES_DB}
+          export POSTGRES_USER=${{ secrets.POSTGRES_USER }}
+          export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
+          export POSTGRES_DB=${{ secrets.POSTGRES_DB }}
 
           docker-compose down
-          POSTGRES_USER=$POSTGRES_USER \
-          POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
-          POSTGRES_DB=$POSTGRES_DB \
+          POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
+          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
+          POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
           docker-compose up -d --build
+          
+          # Configure Nginx
+          cat <<EOL > /etc/nginx/conf.d/attackvisualizer.conf
+          server {
+              listen 80;
+              server_name hack.kevinlockburner.com;
+
+              return 301 https://\$host\$request_uri;
+          }
+
+          server {
+              listen 443 ssl;
+              server_name hack.kevinlockburner.com;
+
+              ssl_certificate /etc/letsencrypt/live/hack.kevinlockburner.com/fullchain.pem;
+              ssl_certificate_key /etc/letsencrypt/live/hack.kevinlockburner.com/privkey.pem;
+
+              ssl_protocols TLSv1.2 TLSv1.3;
+              ssl_ciphers HIGH:!aNULL:!MD5;
+              ssl_prefer_server_ciphers on;
+
+              location /api/ {
+                  proxy_pass http://localhost:8000/;
+                  proxy_set_header Host \$host;
+                  proxy_set_header X-Real-IP \$remote_addr;
+                  proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
+                  proxy_set_header X-Forwarded-Proto \$scheme;
+              }
+
+              location / {
+                  proxy_pass http://localhost:3000/;
+                  proxy_set_header Host \$host;
+                  proxy_set_header X-Real-IP \$remote_addr;
+                  proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
+                  proxy_set_header X-Forwarded-Proto \$scheme;
+              }
+          }
+          EOL
+
+          nginx -t && systemctl reload nginx || (echo "Nginx reload failed"; exit 1)
           EOF
+    
 
 
